### ISSUE TITLE
libable_shim.c:3:10: fatal error: 'able/able.h' file not found

### ISSUE THREAD

**Issue by ulrivo** [ablevm/able#2]
After 

    bmake -DCOMPAT_MACOS install

there is an error message

   libable_shim.c:3:10: fatal error: 'able/able.h' file not found

Regards,
Ulrich

**Comment by marksmith** [comment]
Please could you confirm that you first built and installed [libable](https://github.com/ablevm/libable), which able depends on? It may be that we need to make this dependency clearer in the README.

**Comment by ulrivo** [comment]
Hi,


I did not build libable in advance.

After doing so, I could build able, too.

Thank you very much.

Best regards,
Ulrich

**Comment by marksmith** [comment]
I'm glad you got able to build, @ulrivo. Thanks for reporting the issue, we will clarify the dependency on libable in the README.
